### ISSUE TITLE
Would like to be a contributor

### ISSUE THREAD

**Issue by hmahajanHM** [nkdAgility/TfvcBranchPolicy#1]
https://in.linkedin.com/in/mahajanhemant my LinkedIn profile.

**Comment by MrHinsh** [comment]
Hi Hemant,

 You can fork the repository and submit pull requests to get stuff into Master. Once I see some of the submissions we can discuss tighter cooperation. 

I have not yet implemented much of the code review functionality, but I am currently trying to parody the Git Branch Policy feature in TFS.

What would you like to work on?

-MrHinsh

**Comment by hmahajanHM** [comment]
Any area be it TFS Client model related or WPF related or Policy storage is fine with me. Suggest the immediate next item if any, and then I can start picking few.

**Comment by MrHinsh** [comment]
the next issue for me is enabling the code review paths

NOTE: We need to be very carefull with the binary serilization. All elements should be optional and don't ever delete or rename anything... I have bricked the component many times due to this issue...

**Comment by MrHinsh** [comment]
In fact I have had to work on this this week. I have a customer with that requirement... Should be done by Thursday...
