### ISSUE TITLE
Could we do another release?

### ISSUE THREAD

**Issue by trzombie** [nkdAgility/TfvcBranchPolicy#23]
..after my PR has been merged?

**Comment by MrHinsh** [comment]
Can you please check https://github.com/nkdAgility/TfvcBranchPolicy/releases/tag/untagged-3b4837ba769d1cc87e03 and test?

**Comment by MrHinsh** [comment]
Can you also try to track down why its now 9mb? Did you change the DLL's to 'copy local'?

**Comment by trzombie** [comment]
I'm getting a 404 on that url.

**Comment by trzombie** [comment]
It definitely looks like the 0.3.3 was done with copylocal. I don't understand how that happened. My local builds on both trzombie and master branches are 0.5Mb.

**Comment by trzombie** [comment]
As to functionality I'm good with pushing 0.3.3 to the gallery. I believe both Branch Lock and Code Review polices works as advertised. Have not tested Work Item Linking.

**Comment by MrHinsh** [comment]
DONE
